version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo18@2024
      - POSTGRES_DB=odoorefait18
    restart: always
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      
  odoo18:
    image: odoo:18
    depends_on:
      - db
    ports:
      - "10018:8069"
      - "20018:8072"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo18@2024
    volumes:
      - ./addons:/mnt/extra-addons
    command: -- --init=base --without-demo=all
    restart: always

volumes:
  postgresql_data:
